language: rust

rust:
  - stable
  - nightly

branches:
  only:
    - staging
    - trying
    - master

matrix:
    allow_failures:
        - script: cargo clippy

script:
  - cargo clippy
  - cargo test
  - cargo test --all-features

